[0;33m--- WARNING: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM3 instead...[0m
[0;33m--- idf_monitor on \\.\COM3 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x4008137c: call_start_cpu1 at D:/ESP_IDF/Espressif/frameworks/esp-idf-v5.1.1/components/esp_system/port/cpu_start.c:154
[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m[0m
[0m
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\ESP_IDF\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\__main__.py", line 4, in <module>
    main()
  File "D:\ESP_IDF\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\idf_monitor.py", line 412, in main
    monitor.main_loop()
  File "D:\ESP_IDF\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\idf_monitor.py", line 174, in main_loop
    self._main_loop()
  File "D:\ESP_IDF\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\idf_monitor.py", line 287, in _main_loop
    super()._main_loop()
  File "D:\ESP_IDF\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\idf_monitor.py", line 219, in _main_loop
    self.serial_handler.handle_serial_input(data, self.console_parser, self.coredump,  # type: ignore
  File "D:\ESP_IDF\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\base\serial_handler.py", line 126, in handle_serial_input
    self.logger.handle_possible_pc_address_in_line(line_strip)
  File "D:\ESP_IDF\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\base\logger.py", line 155, in handle_possible_pc_address_in_line
    translation = lookup_pc_address(num, self.toolchain_prefix, self.elf_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ESP_IDF\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\base\output_helpers.py", line 36, in lookup_pc_address
    translation = subprocess.check_output(cmd, cwd='.')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 466, in check_output
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['xtensa-esp32-elf-addr2line', '-pfiaC', '-e', 'D:\\ESP_IDF\\ESP32_project\\tcp\\build\\mqtt_tcp.elf', '0x40080400']' returned non-zero exit status 3221225794.
